[phases.setup]
nixPkgs = ['python3', 'python3Packages.pip']

[phases.install]
cmds = ['python3 -m pip install -r backend/requirements.txt']

[start]
cmd = "uvicorn backend.src.app:app --host=0.0.0.0 --port=8000"