[phases.setup]
nixPkgs = ['python3', 'python3Packages.pip']

[phases.install]
cmds = ['cd backend && python3 -m pip install -r requirements.txt']

[start]
cmd = "cd backend && python3 -m uvicorn src.app:app --host=0.0.0.0 --port=8000"
